alter session set "_ORACLE_SCRIPT"=true;

create user ZAPATERIA identified by 123;
GRANT dba TO ZAPATERIA;
CREATE TABLESPACE TSZAPATERIA
   DATAFILE 'ZAPATERIADF.tbs' SIZE 250M
   AUTOEXTEND ON MAXSIZE 500M;

ALTER SYSTEM SET SGA_TARGET=2000M SCOPE=SPFILE;

ALTER SYSTEM SET PGA_AGGREGATE_TARGET=100M SCOPE=SPFILE;

alter system set processes=1500 scope=spfile;

alter system set sessions=500 scope=spfile;


SELECT * FROM V$MEMORY_DYNAMIC_COMPONENTS;


CREATE ROLE Contabilidad;
GRANT CONNECT TO Contabilidad;
GRANT SELECT, INSERT ANY TABLE TO Contabilidad;


CREATE ROLE Ventas;
GRANT CONNECT TO Ventas;
GRANT SELECT, INSERT ANY TABLE TO Ventas;

CREATE ROLE IT;
GRANT CONNECT TO IT;
GRANT SELECT, DELETE ANY TABLE TO IT;
GRANT CREATE TABLE TO IT;
GRANT CREATE USER TO IT;


CREATE ROLE Gerencia;
GRANT CONNECT TO Gerencia;
GRANT SELECT, INSERT,UPDATE, DELETE ANY TABLE TO Gerencia;
GRANT CREATE USER TO Gerencia;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='Gerencia';


CREATE USER Contabilidad1 IDENTIFIED BY bd2Conta1;
GRANT Contabilidad TO Contabilidad1;
CREATE USER Contabilidad2 IDENTIFIED BY bd2Conta2;
GRANT Contabilidad TO Contabilidad2;

CREATE USER Ventas1 IDENTIFIED BY bd2Ventas1;
GRANT Ventas TO Ventas1;
CREATE USER Ventas2 IDENTIFIED BY bd2Ventas2;
GRANT Ventas TO Ventas2;

CREATE USER IT1  IDENTIFIED BY bd2IT1;
GRANT IT TO IT1;
CREATE USER IT2  IDENTIFIED BY bd2IT2;
GRANT IT TO IT2;

CREATE USER Gerencia1 IDENTIFIED BY bd2Gerencia1;
GRANT Gerencia TO Gerencia1;
CREATE USER Gerencia2 IDENTIFIED BY bd2Gerencia2;
GRANT Gerencia TO Gerencia2;
