alter session set "_ORACLE_SCRIPT"=true;

create user ZAPATERIA identified by 123;
GRANT dba TO ZAPATERIA;
CREATE TABLESPACE TSZAPATERIA
   DATAFILE 'ZAPATERIADF.tbs' SIZE 250M
   AUTOEXTEND ON MAXSIZE 500M;

ALTER SYSTEM SET SGA_TARGET=2000M SCOPE=SPFILE;

ALTER SYSTEM SET PGA_AGGREGATE_TARGET=100M SCOPE=SPFILE;

alter system set processes=1500 scope=spfile;

alter system set sessions=500 scope=spfile;


SELECT * FROM V$MEMORY_DYNAMIC_COMPONENTS;
